### ISSUE TITLE
Cloud9 에서 설치시 오류가 발생합니다. 

### ISSUE THREAD

**Issue by dusskapark** [golbin/node-mecab-ya#1]
[mecab-ya.txt](https://github.com/golbin/node-mecab-ya/files/518744/mecab-ya.txt)

`/mecab-ya/bin/install-mecab.sh ko` 로 설치를 하려고 하면 위와 같이 오류가 발생합니다. 

[cloud9](http://c9.io/) 에서 설치 과정에서 문제가 있었는데, 인스톨 스크립트 문제인 것 같습니다.

**Comment by tael** [comment]
c9를 써보진않았지만 스크립트 수정해서 #2 에서 진행해 봅니다.
